quarkus:
    http:
        port: 6700
    datasource:
        db-kind: postgresql
        username: postgres
        password: admin
        jdbc:
            url: jdbc:tracing:postgresql://localhost:5432/quarkus_icecream
            driver: "io.opentracing.contrib.jdbc.TracingDriver"

    flyway:
        # initiate migration on application bootup
        migrate-at-start: true
        # create flyway history table when none exists
        baseline-on-migrate: true
        # validate migration
        validate-on-migrate: true

    hibernate-orm:
        # enable SQL logs
        log:
            sql: false
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

    # enable debug on project
    log:
        # default to debug
        level: INFO
        console:
            format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, [%c{2.}] (%t)
            %s%e%n"

